name: 🧱 VH Standard GHI
description: Template for general GHI requests
labels: [vh-standard]
assignees: []

body:
  - type: textarea
    id: context
    attributes:
      label: Context
      description: What is the background or situation that led to this request?
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What issue are we trying to solve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What is the proposed solution or next steps?
    validations:
      required: true

  - type: input
    id: priority
    attributes:
      label: Level of Priority
      description: Level of priority for this request (e.g., high, medium, low).

  - type: textarea
    id: specs
    attributes:
      label: Specifications (Optional)
      description: List any known technical specs, parameters, or assumptions.
    validations:
      required: false

  - type: checkboxes
    id: steps
    attributes:
      label: Workflow Steps
      description: Select completed steps or keep as checklist for tracking progress.
      options:
        - label: Define scope and confirm with SME
        - label: Create config or data request
        - label: Run and validate results
        - label: Submit and track download request
        - label: Create and assign pull request for review
        - label: Merge PR and close GHI
